import { employeeDatas } from '../model/interface';

const EMPLOYEE: employeeDatas[] = [{
  id: 1,
  sapId: 52016142,
  designation: 'Senior Technical Manager',
  text: 'Vinesh Manik',
  email:'vinesh.manik@hcl.com',
  gender: 'Male',
  contact: 9560062746,
  employeeStatus: 'Active',
  image: 'https://www.w3schools.com/howto/img_avatar.png',
  location:"Noida",
  rm: 'Azeem Ahmad',
  role: 'Senior Tecnical Manager'

},
{
  id: 2,
  sapId: 51870046,
  designation: 'Senior Technical Lead',
  text: 'Vipin Kumar Mangalam',
  role: "Front-End Developer",
  email:'vipinkumar.mangalam@hcl.com',
  gender: 'Male',
  rm: 'Vinesh Manik',
  image: 'https://www.w3schools.com/howto/img_avatar.png',
  location:"Noida",
  contact: 9844441689,
  employeeStatus: 'Active'
},
{
  id: 3,
  sapId: 52100507,
  designation: 'lead Engineer',
  text: 'Basavaraja Hiruru',
  role: "Front-End Developer",
  email:'basavaraja.hiruru@hcl.com',
  gender: 'Male',
  rm: 'Vipin Kumar Mangalam',
  image: 'https://www.w3schools.com/howto/img_avatar.png',
  location:"Bangalore",
  contact: 7760744746,
  employeeStatus: 'Active'
},
{
  id: 4,
  sapId: 51898957,
  designation: 'lead Engineer',
  text: 'Mohuya Banerjee',
  role: "Front-End Developer",
  email:'mohuya.banerjee@hcl.com',
  gender: 'Female',
  rm: 'Vipin Kumar Mangalam',
  image: 'https://www.w3schools.com/howto/img_avatar2.png',
  location:"Noida",
  contact: 9563011118,
  employeeStatus: 'Active'
},
{
  id: 5,
  sapId:52078333,
  designation: 'lead Engineer',
  text: 'Ravindra Kumar',
  role: "Front-End Developer",
  email:'ravindra.k@hcl.com',
  gender: 'Male',
  rm: 'Vipin Kumar Mangalam',
  image: 'https://www.w3schools.com/howto/img_avatar.png',
  location:"Noida",
  contact: 7903273700,
  employeeStatus: 'Active'
},
{
  id: 6,
  sapId: 52048586,
  text: 'Himanshu Agarwal',
  role: "Back-End Developer",
  designation: 'Senior Technical Lead',
  email:'himanshu-agarwal@hcl.com',
  gender: 'Male',
  rm: 'Vinesh Manik',
  image: 'https://www.w3schools.com/howto/img_avatar.png',
  location:"Noida",
  contact: 8368334049,
  employeeStatus: 'Active',

},
{
  id: 7,
  sapId: 52111994,
  text: 'Manu Tomer',
  role: "Back-End Developer",
  designation: 'Technical lead',
  email:'manu.tomer@hcl.com',
  gender: 'Male',
  rm: 'Himanshu Agarwal',
  image: 'https://www.w3schools.com/howto/img_avatar.png',
  location:"Noida",
  contact: 882-661-5730,
  employeeStatus: 'Active',
},
{
  id: 8,
  sapId: 52109067,
  text: 'Pilli Naveen',
  role: "Back-End Developer",
  designation: 'Lead Engineer',
  email:'pilli.naveen@hcl.com',
  gender: 'Male',
  rm: 'Himanshu Agarwal',
  image: 'https://www.w3schools.com/howto/img_avatar.png',
  location:"Noida",
  contact: 9108036561,
  employeeStatus: 'Active'
},
{
  id: 9,
  sapId:52102422,
  text: 'Tanish Sharma',
  role: "Back-End Developer",
  designation: 'Lead Engineer',
  email:'tanish.sharma@hcl.com',
  gender: 'Male',
  rm: 'Himanshu Agarwal',
  contact: 9589042013,
  image: 'https://www.w3schools.com/howto/img_avatar.png',
  location:"Noida",
  employeeStatus: 'Active'
},
{
  id: 10,
  sapId:52022131,
  text: 'Arindam Maji',
  role: "Full-Stack Developer",
  designation: 'Software Engineer',
  email:'arindam.maji@hcl.com',
  gender: 'Male',
  rm: 'Himanshu Agarwal',
  image: 'https://www.w3schools.com/howto/img_avatar.png',
  location:"Noida",
  contact: 7908582628,
  employeeStatus: 'Active'
},
{
  id: 11,
  sapId:52051212,
  text: 'Rekha Adeen',
  role: "Back-End Developer",
  designation: 'Lead Engineer',
  email:'rekha.adeen@hcl.com',
  gender: 'Female',
  image: 'https://www.w3schools.com/howto/img_avatar2.png',
  location:"Noida",
  rm: 'Himanshu Agarwal',
  contact: 8431008028,
  employeeStatus: 'Active'
},
{
  id: 12,
  sapId: 52110412,
  text: 'Vandana Kumari',
  role: "Test Engineer",
  designation: 'Technical Lead',
  email:'vandana-kumari@hcl.com',
  gender: 'Female',
  rm: 'Vinesh Manik',
  image: 'https://www.w3schools.com/howto/img_avatar2.png',
  location:"Noida",
  contact: 7397250477,
  employeeStatus: 'Active'
},
{
  id: 13,
  sapId: 52005403,
  text: 'Smaraki Mohanty',
  role: "Test Engineer",
  designation: 'lead Engineer',
  email:'smaraki.mohanty@hcl.com',
  gender: 'Female',
  rm: 'Vandana Kumari',
  image: 'https://www.w3schools.com/howto/img_avatar2.png',
  location:"Noida",
  contact: 9886061752,
  employeeStatus: 'Active'
}
];

export default EMPLOYEE;
